// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practica_1.Models;

namespace Practica_1.Migrations
{
    [DbContext(typeof(ImpuestoContext))]
    partial class ImpuestoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Practica_1.Models.Impuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Grados")
                        .HasColumnType("int");

                    b.Property<int>("NumeroLiquidacion")
                        .HasColumnType("int");

                    b.Property<int>("ValorImpuesto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Impuestos");
                });
#pragma warning restore 612, 618
        }
    }
}
